### ISSUE TITLE
pip install fails: "UnicodeDecodeError" (Debian stretch) 

### ISSUE THREAD

**Issue by pafodie** [chrisjbillington/inotify_simple#13]
With version 1.2.0, I'm not able to install inotify_simple via pip. I'm using Debian 9.8 inside an example docker:

```
root@572a1841de00:/io# pip3 install inotify_simple --no-cache-dir
Collecting inotify_simple
  Downloading https://files.pythonhosted.org/packages/4d/ac/60130ad6febe12e4900da453cac7cbe0a0b504fd0a9a1fbd500991c30f37/inotify_simple-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ufjztwut/inotify-simple/setup.py", line 29, in <module>
        long_description=open('README').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1587: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ufjztwut/inotify-simple/
```

`pip3 install inotify_simple==1.1.8 --no-cache-dir` works, though.

**Comment by chrisjbillington** [comment]
Oh, there's a non-ascii character in the README and Python 2 isn't happy about it. Pandoc converted quotes to "smart quotes" in the generation of that README file, I guess it didn't previously do that.

Sorry, will fix!

**Comment by chrisjbillington** [comment]
Oh I see, you're on Python 3, but `locale.getpreferredencoding()` is ASCII.

**Comment by chrisjbillington** [comment]
FIxed in v1.2.1

**Comment by pafodie** [comment]
Amazing fixing time, thank you! Can confirm that it works now inside the same environment.

**Comment by chrisjbillington** [comment]
:)
