### ISSUE TITLE
add_watch does not support pathlib.Path objects

### ISSUE THREAD

**Issue by ali1234** [chrisjbillington/inotify_simple#4]
Contrary to the documentation, passing a Path to add_watch() does not work:

```
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from inotify_simple import INotify, flags
>>> i = INotify()
>>> import pathlib
>>> i.add_watch(pathlib.Path('/tmp'), flags.CREATE | flags.DELETE | flags.MODIFY | flags.DELETE_SELF)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/al/.local/lib/python3.5/site-packages/inotify_simple/inotify_simple.py", line 86, in add_watch
    path = _fsencode(path)
  File "/usr/lib/python3.5/os.py", line 862, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not PosixPath
```

Installed with: pip3 install inotify_simple

**Comment by chrisjbillington** [comment]
Thanks for the report.

Looks like `os.fsencode()` only started accepting Path objects in [Python 3.6](https://docs.python.org/3/library/os.html#os.fsencode). So I'll need to fix this for Python < 3.6.

**Comment by chrisjbillington** [comment]
Should be fixed, please let me know if the latest release doesn't fix the issue for you.

**Comment by ali1234** [comment]
It works for me, thanks.
